package main

import (
	"bufio"
	"bytes"
	"crypto/rand"
	"crypto/subtle"
	"embed"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"html"
	"io"
	"io/fs"
	"net"
	"net/url"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/go-webauthn/webauthn/webauthn"
	"github.com/schappim/mygrok/internal/branding"
)

// adminSessions is an in-memory store of active admin session cookies.
// It survives process lifetime only — restart and you re-login. Each
// entry is a random 32-byte hex token mapped to its expiry.
type adminSessions struct {
	mu sync.Mutex
	m  map[string]time.Time
}

var adminSess = &adminSessions{m: map[string]time.Time{}}

const adminCookieName = "mygrok_admin"
const adminSessionTTL = 24 * time.Hour

func (s *adminSessions) issue() string {
	var b [32]byte
	if _, err := rand.Read(b[:]); err != nil {
		// Fall back to time-based — extremely unlikely path.
		return fmt.Sprintf("t-%d", time.Now().UnixNano())
	}
	id := hex.EncodeToString(b[:])
	s.mu.Lock()
	s.m[id] = time.Now().Add(adminSessionTTL)
	s.mu.Unlock()
	return id
}

func (s *adminSessions) valid(id string) bool {
	if id == "" {
		return false
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	exp, ok := s.m[id]
	if !ok {
		return false
	}
	if time.Now().After(exp) {
		delete(s.m, id)
		return false
	}
	return true
}

// Embedded mygrok client binaries, built before mygrokd is built.
// Filenames in dist/ are copied here and named mygrok-<os>-<arch>.
//
//go:embed embed/clients/*
var clientFS embed.FS

// installScript is shipped at GET /install. It detects OS/arch, downloads
// the matching binary from /dl, and installs it to /usr/local/bin/mygrok
// (or $MYGROK_INSTALL_DIR if set).
const installScript = `#!/usr/bin/env bash
set -euo pipefail
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)
case "$ARCH" in
  x86_64|amd64) ARCH=amd64 ;;
  aarch64|arm64) ARCH=arm64 ;;
  armv7l|armhf) echo "armhf not supported yet"; exit 1 ;;
  *) echo "unsupported arch: $ARCH" >&2; exit 1 ;;
esac
case "$OS" in
  darwin|linux) ;;
  *) echo "unsupported OS: $OS" >&2; exit 1 ;;
esac
DEST="${MYGROK_INSTALL_DIR:-/usr/local/bin}"
URL="https://%[1]s/dl/mygrok-${OS}-${ARCH}"
TMP=$(mktemp)
echo ">> downloading mygrok ${OS}/${ARCH} from $URL"
curl -fsSL "$URL" -o "$TMP"
# Use install(1) so the destination gets a fresh inode. macOS will
# SIGKILL an ad-hoc-signed Go binary that lands at an inode the kernel
# previously cached as "won't run", which is what happens if you cp/mv
# over an existing copy.
if [ -w "$DEST" ]; then
  install -m 0755 "$TMP" "$DEST/mygrok"
else
  echo ">> sudo install to $DEST/mygrok"
  sudo install -m 0755 "$TMP" "$DEST/mygrok"
fi
rm -f "$TMP"

# Point the client at this server.
#
# Binaries built by build.sh have the address linked in, but release builds
# are deliberately generic — they must not ship pointing at anyone's server.
# Since this script is generated by the server the user is installing from,
# it knows the right answer, so it writes a config rather than leaving the
# very next command to fail with "no tunnel server configured".
#
# Only ever creates the file; an existing config is left alone.
HOME_DIR="$HOME"
if [ -n "${SUDO_USER:-}" ] && [ "$(id -u)" = "0" ]; then
  HOME_DIR="$(eval echo "~$SUDO_USER")"
fi
CONFIG="$HOME_DIR/.mygrok/config.toml"
if [ ! -e "$CONFIG" ]; then
  mkdir -p "$(dirname "$CONFIG")"
  printf 'server = "%[2]s"\n' > "$CONFIG"
  chmod 600 "$CONFIG"
  if [ -n "${SUDO_USER:-}" ] && [ "$(id -u)" = "0" ]; then
    chown -R "$SUDO_USER" "$(dirname "$CONFIG")"
  fi
  echo ">> wrote $CONFIG (server = %[2]s)"
fi

echo
echo "  installed: $DEST/mygrok"
echo
echo "  next:"
echo "    export MYGROK_AUTHTOKEN=<your-token>"
echo "    mygrok http 3000 --subdomain=foo"
echo
`

// faviconSVG is sourced from the shared branding package so the CLI's
// `mygrok serve` fallback uses the same icon as the admin / offline pages.
const faviconSVG = branding.FaviconSVG

// offlinePage is rendered when a public request hits a subdomain that has
// no active tunnel. Mirrors ngrok's "tunnel offline" UX.
const offlinePage = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<title>Tunnel offline · %[1]s</title>
<style>
  :root {
    color-scheme: dark light;
    --bg: #07090d;
    --bg-grid: rgba(120,140,170,0.05);
    --panel: #0d1119;
    --panel-2: #11151f;
    --hairline: #1a2030;
    --hairline-2: #2a3245;
    --ink: #e7eaf2;
    --ink-dim: #8a93a6;
    --ink-dimmer: #5b6478;
    --signal: #b8f068;
    --signal-soft: rgba(184,240,104,0.10);
    --signal-line: rgba(184,240,104,0.35);
    --danger: #ff8a8a;
    --danger-soft: rgba(255,138,138,0.10);
    --danger-line: rgba(255,138,138,0.35);
  }
  @media (prefers-color-scheme: light) {
    :root {
      --bg: #f7f5f0; --bg-grid: rgba(20,30,50,0.06);
      --panel: #ffffff; --panel-2: #f1efe9;
      --hairline: #e3dfd5; --hairline-2: #cbc6b8;
      --ink: #1a1d24; --ink-dim: #5b6175; --ink-dimmer: #8a8f9d;
      --signal: #2f7a2f; --signal-soft: rgba(47,122,47,0.08); --signal-line: rgba(47,122,47,0.30);
      --danger: #b3261e; --danger-soft: rgba(179,38,30,0.06); --danger-line: rgba(179,38,30,0.28);
    }
  }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; }
  body {
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-feature-settings: "calt", "ss01";
    font-size: 14px; line-height: 1.55;
    background: var(--bg); color: var(--ink);
    min-height: 100vh;
    background-image: radial-gradient(circle at 1px 1px, var(--bg-grid) 1px, transparent 0);
    background-size: 24px 24px; background-position: -1px -1px;
    -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;
  }
  ::selection { background: var(--danger); color: var(--bg); }
  .wrap { max-width: 720px; margin: 0 auto; padding: 64px 24px 64px; }

  .status {
    display: inline-flex; align-items: center; gap: 10px;
    font-size: 11px; letter-spacing: 0.20em; text-transform: uppercase;
    color: var(--danger); font-weight: 600;
    padding: 6px 12px; border: 1px solid var(--danger-line);
    background: var(--danger-soft); border-radius: 3px;
  }
  .status::before {
    content: ""; width: 6px; height: 6px; border-radius: 50%%;
    background: var(--danger); box-shadow: 0 0 8px var(--danger);
  }

  h1 {
    font-family: ui-monospace, monospace;
    font-weight: 700; font-size: 32px; letter-spacing: -0.02em;
    margin: 22px 0 10px; word-break: break-all;
  }
  p { font-size: 14px; line-height: 1.65; color: var(--ink-dim); margin: 0 0 14px; }

  code {
    font-family: ui-monospace, monospace;
    font-size: 12.5px; font-weight: 500;
    background: var(--panel-2); color: var(--ink);
    padding: 2px 8px; border: 1px solid var(--hairline-2); border-radius: 3px;
  }

  .card {
    background: var(--panel);
    border: 1px solid var(--hairline);
    border-radius: 6px;
    padding: 22px 26px 24px; margin: 28px 0;
    position: relative;
  }
  .card::before {
    content: ""; position: absolute; inset: 0; border-radius: 6px;
    pointer-events: none; box-shadow: inset 0 1px 0 rgba(255,255,255,0.03);
  }
  .card h2 {
    font-size: 11px; letter-spacing: 0.20em; text-transform: uppercase;
    color: var(--ink); margin: 0 0 14px; font-weight: 700;
  }

  pre {
    font-family: ui-monospace, monospace;
    font-size: 13px; line-height: 1.6;
    background: var(--bg); color: var(--ink);
    border: 1px solid var(--hairline-2);
    border-radius: 4px;
    padding: 14px 18px; margin: 0; overflow-x: auto;
    position: relative;
  }
  pre::before {
    content: "$"; color: var(--signal); margin-right: 10px; font-weight: 600;
  }
  pre.no-prompt::before { content: ""; margin: 0; }

  .footer {
    margin-top: 56px; padding-top: 20px;
    border-top: 1px dashed var(--hairline-2);
    font-size: 11.5px; letter-spacing: 0.04em;
    color: var(--ink-dimmer);
  }
  .footer a { color: var(--ink-dim); border-bottom: 1px solid var(--hairline-2); text-decoration: none; transition: color 120ms, border-color 120ms; }
  .footer a:hover { color: var(--signal); border-bottom-color: var(--signal); }

  @media (max-width: 600px) {
    .wrap { padding: 40px 16px 48px; }
    h1 { font-size: 24px; }
    .card { padding: 18px 18px 20px; }
  }
</style>
</head>
<body>
<div class="wrap">
  <span class="status">Tunnel offline</span>
  <h1>%[1]s</h1>
  <p>No <code>mygrok</code> client is currently connected for this hostname. The tunnel will come back online as soon as a client registers.</p>
  <div class="card">
    <h2>Bring this tunnel up</h2>
    <pre>mygrok http &lt;port&gt; --subdomain=%[2]s</pre>
  </div>
  <p>Don't have <code>mygrok</code> yet?</p>
  <pre>curl -sSL https://%[3]s/install | bash</pre>
  <p class="footer">mygrok · DIY tunnel · <a href="https://%[3]s/">%[3]s</a></p>
</div>
</body>
</html>`

const landingPage = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<title>mygrok · %[1]s</title>
<style>
  :root {
    color-scheme: dark light;
    --bg: #07090d;
    --bg-grid: rgba(120,140,170,0.05);
    --panel: #0d1119;
    --panel-2: #11151f;
    --hairline: #1a2030;
    --hairline-2: #2a3245;
    --ink: #e7eaf2;
    --ink-dim: #8a93a6;
    --ink-dimmer: #5b6478;
    --signal: #b8f068;
    --signal-soft: rgba(184,240,104,0.10);
    --signal-line: rgba(184,240,104,0.35);
  }
  @media (prefers-color-scheme: light) {
    :root {
      --bg: #f7f5f0; --bg-grid: rgba(20,30,50,0.06);
      --panel: #ffffff; --panel-2: #f1efe9;
      --hairline: #e3dfd5; --hairline-2: #cbc6b8;
      --ink: #1a1d24; --ink-dim: #5b6175; --ink-dimmer: #8a8f9d;
      --signal: #2f7a2f; --signal-soft: rgba(47,122,47,0.08); --signal-line: rgba(47,122,47,0.30);
    }
  }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; }
  body {
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-feature-settings: "calt", "ss01";
    font-size: 14px; line-height: 1.55;
    background: var(--bg); color: var(--ink);
    min-height: 100vh;
    background-image: radial-gradient(circle at 1px 1px, var(--bg-grid) 1px, transparent 0);
    background-size: 24px 24px; background-position: -1px -1px;
    -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;
  }
  ::selection { background: var(--signal); color: var(--bg); }
  .wrap { max-width: 720px; margin: 0 auto; padding: 64px 24px 64px; }

  @keyframes pulse { 0%%,100%% { opacity: 1; } 50%% { opacity: 0.35; } }

  .status {
    display: inline-flex; align-items: center; gap: 10px;
    font-size: 11px; letter-spacing: 0.20em; text-transform: uppercase;
    color: var(--signal); font-weight: 600;
    padding: 6px 12px; border: 1px solid var(--signal-line);
    background: var(--signal-soft); border-radius: 3px;
  }
  .status::before {
    content: ""; width: 6px; height: 6px; border-radius: 50%%;
    background: var(--signal); box-shadow: 0 0 8px var(--signal);
    animation: pulse 2.4s ease-in-out infinite;
  }

  h1 {
    font-family: ui-monospace, monospace;
    font-weight: 800; font-size: 56px; letter-spacing: -0.04em;
    margin: 24px 0 4px; line-height: 1.05;
  }
  .tagline {
    font-size: 15px; line-height: 1.65;
    color: var(--ink-dim); margin: 12px 0 36px; max-width: 56ch;
  }
  p { font-size: 14px; line-height: 1.65; color: var(--ink-dim); margin: 0 0 12px; }

  code {
    font-family: ui-monospace, monospace;
    font-size: 12.5px; font-weight: 500;
    background: var(--panel-2); color: var(--ink);
    padding: 2px 8px; border: 1px solid var(--hairline-2); border-radius: 3px;
  }

  .step {
    background: var(--panel); border: 1px solid var(--hairline);
    border-radius: 6px; padding: 22px 26px 22px;
    margin: 14px 0; position: relative;
  }
  .step::before {
    content: ""; position: absolute; inset: 0; border-radius: 6px;
    pointer-events: none; box-shadow: inset 0 1px 0 rgba(255,255,255,0.03);
  }
  .step-head {
    display: flex; align-items: center; gap: 14px; margin-bottom: 14px;
  }
  .step-num {
    font-family: ui-monospace, monospace;
    font-size: 11px; font-weight: 600; letter-spacing: 0.10em;
    color: var(--signal); padding: 3px 8px;
    background: var(--signal-soft); border: 1px solid var(--signal-line);
    border-radius: 3px;
  }
  .step-title {
    font-size: 11px; letter-spacing: 0.20em; text-transform: uppercase;
    color: var(--ink); font-weight: 700;
  }

  pre {
    font-family: ui-monospace, monospace;
    font-size: 13px; line-height: 1.65;
    background: var(--bg); color: var(--ink);
    border: 1px solid var(--hairline-2);
    border-radius: 4px;
    padding: 14px 18px; margin: 0; overflow-x: auto;
  }
  pre .prompt { color: var(--signal); font-weight: 600; user-select: none; }
  pre .arrow  { color: var(--ink-dimmer); }
  pre .url    { color: var(--ink); }
  pre .flag   { color: var(--ink-dim); }

  .footer {
    margin-top: 56px; padding-top: 20px;
    border-top: 1px dashed var(--hairline-2);
    font-size: 11.5px; letter-spacing: 0.04em;
    color: var(--ink-dimmer);
  }
  .footer a { color: var(--ink-dim); border-bottom: 1px solid var(--hairline-2); text-decoration: none; transition: color 120ms, border-color 120ms; }
  .footer a:hover { color: var(--signal); border-bottom-color: var(--signal); }

  @media (max-width: 600px) {
    .wrap { padding: 40px 16px 48px; }
    h1 { font-size: 40px; }
    .step { padding: 18px 18px 18px; }
  }
</style>
</head>
<body>
<div class="wrap">
  <span class="status">DIY tunnel</span>
  <h1>mygrok</h1>
  <p class="tagline">A self-hosted tunnel server. Forward any local port to a public HTTPS URL on your own domain.</p>
  <div class="step">
    <div class="step-head"><span class="step-num">01</span><span class="step-title">Install the client</span></div>
    <pre><span class="prompt">$</span> curl -sSL https://%[1]s/install | bash</pre>
  </div>
  <div class="step">
    <div class="step-head"><span class="step-num">02</span><span class="step-title">Forward a local port</span></div>
    <pre><span class="prompt">$</span> mygrok http 3000 <span class="flag">--subdomain=foo</span>
<span class="arrow">  →</span> <span class="url">https://foo.%[2]s</span></pre>
  </div>
  <p class="footer">mygrok · self-hosted tunnels · <a href="https://github.com/schappim/mygrok">github.com/schappim/mygrok</a></p>
</div>
</body>
</html>`

// isManagementHost reports whether host (no port) targets the server's own
// management endpoints (install script, downloads, landing) rather than a
// user tunnel.
func isManagementHost(hostNoPort, publicHost string) bool {
	mgmt := "tunnel." + publicHost
	return hostNoPort == mgmt
}

// serveAdmin handles requests to tunnel.<publicHost>.
//
//	GET  /install                   → bash installer
//	GET  /dl/mygrok-<os>-<arch>     → embedded client binary
//	GET  /admin/ips                 → overview: global rules + tunnel list
//	GET  /admin/ips?key=<token>     → magic-link login (issues cookie, redirects)
//	POST /admin/ips                 → add/remove a global entry
//	GET  /admin/ips/<subdomain>     → per-tunnel allow/block rules
//	POST /admin/ips/<subdomain>     → add/remove a per-tunnel entry
//	GET  /admin/passkeys            → passkey management UI
//	POST /admin/passkeys/begin      → start registration (JSON challenge)
//	POST /admin/passkeys/finish     → finish registration
//	POST /admin/passkeys/delete     → revoke one credential
//	POST /admin/locks               → toggle a tunnel's require-passkey flag
//	GET  /auth                      → passkey login UI
//	POST /auth/begin                → start assertion (JSON challenge)
//	POST /auth/finish               → finish assertion (sets session cookie)
//	GET  /auth/logout               → clear session cookie
//	anything else                   → landing page
//
// rawHeaders is the captured request bytes; br has the rest of the
// connection (used to read POST bodies on the admin pages).
func serveAdmin(conn net.Conn, rawHeaders []byte, br *bufio.Reader, acl *ipACL, reg *registry, pks *passkeyStore, wa *webauthn.WebAuthn, locks *tunnelLocks, invites *inviteStore) {
	defer conn.Close()
	method, fullURI := parseRequestLine(rawHeaders)
	path := fullURI
	rawQuery := ""
	if i := strings.Index(fullURI, "?"); i >= 0 {
		path = fullURI[:i]
		rawQuery = fullURI[i+1:]
	}
	host := "tunnel." + *publicHost

	// Every mutation on this host goes through POST. Reject cross-site ones
	// before any handler runs, rather than remembering to check in each of
	// the dozen POST branches below.
	if method == "POST" && !sameOriginPOST(rawHeaders, *publicHost) {
		writeHTTP(conn, 403, "text/plain; charset=utf-8",
			[]byte("cross-site request rejected\n"))
		return
	}

	switch {
	case path == "/install":
		body := []byte(fmt.Sprintf(installScript, host, clientServerAddr()))
		writeHTTP(conn, 200, "text/plain; charset=utf-8", body)
	case path == "/favicon.ico" || path == "/favicon.svg":
		writeHTTP(conn, 200, "image/svg+xml", []byte(faviconSVG))
	case strings.HasPrefix(path, "/dl/"):
		name := strings.TrimPrefix(path, "/dl/")
		serveBinary(conn, name)
	case path == "/admin" || path == "/admin/":
		writeHTTPRedirect(conn, "/admin/ips")
	case path == "/admin/ips":
		serveAdminIPs(conn, method, rawQuery, rawHeaders, br, acl, reg)
	case strings.HasPrefix(path, "/admin/ips/"):
		sub := strings.TrimPrefix(path, "/admin/ips/")
		serveAdminTunnelIPs(conn, method, sub, rawHeaders, br, acl, reg, locks, pks)
	case path == "/admin/passkeys":
		serveAdminPasskeys(conn, method, rawHeaders, br, pks, wa)
	case path == "/admin/passkeys/begin":
		serveAdminPasskeyBegin(conn, rawHeaders, br, pks, wa)
	case path == "/admin/passkeys/finish":
		serveAdminPasskeyFinish(conn, rawHeaders, br, pks, wa)
	case path == "/admin/passkeys/delete":
		serveAdminPasskeyDelete(conn, rawHeaders, br, pks)
	case path == "/admin/users":
		serveAdminUsers(conn, method, rawHeaders, br, pks, locks, invites)
	case path == "/admin/users/delete":
		serveAdminUsersDelete(conn, rawHeaders, br, pks, locks)
	case path == "/admin/invites":
		serveAdminInvites(conn, method, rawHeaders, br, invites)
	case path == "/admin/invites/create":
		serveAdminInvitesCreate(conn, rawHeaders, br, invites)
	case path == "/admin/locks":
		serveAdminLocks(conn, rawHeaders, br, locks, pks)
	case path == "/admin/grants":
		serveAdminGrants(conn, rawHeaders, br, locks, pks)
	case strings.HasPrefix(path, "/invite/"):
		serveInvite(conn, path, method, rawHeaders, br, pks, wa, invites)
	case path == "/auth":
		serveAuth(conn, rawQuery, rawHeaders, pks)
	case path == "/auth/begin":
		serveAuthBegin(conn, rawQuery, rawHeaders, br, pks, wa)
	case path == "/auth/finish":
		serveAuthFinish(conn, rawHeaders, br, pks, wa)
	case path == "/auth/logout":
		serveAuthLogout(conn, rawQuery, rawHeaders, pks)
	case path == "/account":
		serveAccount(conn, method, rawQuery, rawHeaders, br, pks, wa)
	case path == "/account/register/begin":
		serveAccountRegisterBegin(conn, rawHeaders, br, pks, wa)
	case path == "/account/register/finish":
		serveAccountRegisterFinish(conn, rawHeaders, br, pks, wa)
	case path == "/account/credentials/delete":
		serveAccountCredentialDelete(conn, rawHeaders, br, pks)
	default:
		writeHTTP(conn, 200, "text/html; charset=utf-8",
			[]byte(fmt.Sprintf(landingPage, host, *publicHost)))
	}
}

// serveAdminIPs renders the overview (global rules + tunnel list) on
// GET and applies a global add/remove on POST. Honors content
// negotiation: with `Accept: application/json` it returns / accepts
// JSON; otherwise it returns HTML.
//
// Auth is either:
//   - a valid mygrok_admin session cookie (set by magic-link login), or
//   - HTTP basic auth (username ignored, password = MYGROK_AUTHTOKEN), or
//   - ?key=<MYGROK_AUTHTOKEN> on the URL — magic-link login (HTML only;
//     CLI clients use HTTP basic).
func serveAdminIPs(conn net.Conn, method, rawQuery string, rawHeaders []byte, br *bufio.Reader, acl *ipACL, reg *registry) {
	if rawQuery != "" {
		if q, err := url.ParseQuery(rawQuery); err == nil {
			if key := q.Get("key"); key != "" && *authToken != "" &&
				subtle.ConstantTimeCompare([]byte(key), []byte(*authToken)) == 1 {
				sid := adminSess.issue()
				writeHTTPLoginRedirect(conn, "/admin/ips", sid)
				return
			}
		}
	}
	if !adminAuthOK(rawHeaders) {
		writeHTTPUnauthorized(conn)
		return
	}
	asJSON := wantsJSON(rawHeaders)
	if method == "POST" {
		flash, class := applyACLMutation(acl, "global", rawHeaders, br)
		if asJSON {
			writeAdminMutateJSON(conn, flash, class)
			return
		}
		writeHTTP(conn, 200, "text/html; charset=utf-8",
			renderAdminOverview(acl, reg, flash, class))
		return
	}
	if asJSON {
		writeAdminStateJSON(conn, acl, reg)
		return
	}
	writeHTTP(conn, 200, "text/html; charset=utf-8",
		renderAdminOverview(acl, reg, "", ""))
}

// serveAdminTunnelIPs handles /admin/ips/<sub> — per-tunnel allow/block
// rules. The subdomain is taken from the URL path (so the form action
// can be a relative POST without an explicit hidden field). Same JSON
// content negotiation as serveAdminIPs.
func serveAdminTunnelIPs(conn net.Conn, method, sub string, rawHeaders []byte, br *bufio.Reader, acl *ipACL, reg *registry, locks *tunnelLocks, pks *passkeyStore) {
	if !adminAuthOK(rawHeaders) {
		writeHTTPUnauthorized(conn)
		return
	}
	if !looksLikeSubdomain(sub) {
		if wantsJSON(rawHeaders) {
			writeHTTP(conn, 400, "application/json",
				[]byte(`{"ok":false,"error":"invalid subdomain in URL"}`))
			return
		}
		writeHTTP(conn, 400, "text/plain; charset=utf-8", []byte("invalid subdomain in URL"))
		return
	}
	asJSON := wantsJSON(rawHeaders)
	if method == "POST" {
		flash, class := applyACLMutation(acl, sub, rawHeaders, br)
		if asJSON {
			writeAdminMutateJSON(conn, flash, class)
			return
		}
		writeHTTP(conn, 200, "text/html; charset=utf-8",
			renderAdminTunnelPage(sub, acl, reg, locks, pks, flash, class))
		return
	}
	if asJSON {
		writeAdminTunnelJSON(conn, sub, acl, reg, locks, pks)
		return
	}
	writeHTTP(conn, 200, "text/html; charset=utf-8",
		renderAdminTunnelPage(sub, acl, reg, locks, pks, "", ""))
}

// wantsJSON reports whether the client asked for JSON via Accept.
func wantsJSON(rawHeaders []byte) bool {
	for _, line := range strings.Split(string(rawHeaders), "\r\n") {
		if !strings.HasPrefix(strings.ToLower(line), "accept:") {
			continue
		}
		v := strings.ToLower(line[len("accept:"):])
		return strings.Contains(v, "application/json")
	}
	return false
}

// writeAdminStateJSON renders the global+tunnels admin state as JSON.
// Schema is documented in `mygrok admin help`. public_host is included
// so the CLI can build clickable URLs without re-deriving them from
// --server.
func writeAdminStateJSON(conn net.Conn, acl *ipACL, reg *registry) {
	type stateOut struct {
		PublicHost        string              `json:"public_host"`
		Global            ipBucket            `json:"global"`
		TunnelsConfigured map[string]ipBucket `json:"tunnels_configured"`
		TunnelsLive       []string            `json:"tunnels_live"`
	}
	out := stateOut{
		PublicHost:        *publicHost,
		Global:            acl.SnapshotGlobal(),
		TunnelsConfigured: map[string]ipBucket{},
		TunnelsLive:       reg.activeSubdomains(),
	}
	for _, sub := range acl.TunnelsConfigured() {
		out.TunnelsConfigured[sub] = acl.SnapshotTunnel(sub)
	}
	b, _ := jsonMarshal(out)
	writeHTTP(conn, 200, "application/json", b)
}

// writeAdminTunnelJSON renders a single tunnel's bucket plus live and
// access-list state.
func writeAdminTunnelJSON(conn net.Conn, sub string, acl *ipACL, reg *registry, locks *tunnelLocks, pks *passkeyStore) {
	type allowedUser struct {
		ID   string `json:"id"`
		Name string `json:"name"`
	}
	type tunnelOut struct {
		Scope          string        `json:"scope"`
		Live           bool          `json:"live"`
		RequirePasskey bool          `json:"require_passkey"`
		AllowedUsers   []allowedUser `json:"allowed_users"`
		Allowed        []ipEntry     `json:"allowed"`
		Blocked        []ipEntry     `json:"blocked"`
	}
	bk := acl.SnapshotTunnel(sub)
	out := tunnelOut{
		Scope:          sub,
		Live:           reg.get(sub) != nil,
		RequirePasskey: locks.IsLocked(sub),
		AllowedUsers:   []allowedUser{},
		Allowed:        bk.Allowed,
		Blocked:        bk.Blocked,
	}
	for _, uid := range locks.AllowedUsers(sub) {
		name := ""
		if u := pks.FindUser(uid); u != nil {
			name = u.Name
		}
		out.AllowedUsers = append(out.AllowedUsers, allowedUser{ID: uid, Name: name})
	}
	if out.Allowed == nil {
		out.Allowed = []ipEntry{}
	}
	if out.Blocked == nil {
		out.Blocked = []ipEntry{}
	}
	b, _ := jsonMarshal(out)
	writeHTTP(conn, 200, "application/json", b)
}

// writeAdminMutateJSON renders the standard {ok, message|error} body
// returned from POSTs that ask for JSON.
func writeAdminMutateJSON(conn net.Conn, flash, class string) {
	type out struct {
		OK      bool   `json:"ok"`
		Message string `json:"message,omitempty"`
		Error   string `json:"error,omitempty"`
	}
	if class == "err" {
		b, _ := jsonMarshal(out{OK: false, Error: flash})
		writeHTTP(conn, 400, "application/json", b)
		return
	}
	b, _ := jsonMarshal(out{OK: true, Message: flash})
	writeHTTP(conn, 200, "application/json", b)
}

// jsonMarshal — small wrapper around encoding/json.
func jsonMarshal(v any) ([]byte, error) { return json.MarshalIndent(v, "", "  ") }

// applyACLMutation reads a POST form and applies the requested
// add/remove on the given scope. Returns a flash message + class.
func applyACLMutation(acl *ipACL, scope string, rawHeaders []byte, br *bufio.Reader) (string, string) {
	form, err := readPostForm(rawHeaders, br)
	if err != nil {
		return "could not parse form: " + err.Error(), "err"
	}
	list := form.Get("list")
	op := form.Get("op")
	val := strings.TrimSpace(form.Get("value"))
	note := form.Get("note")
	switch op {
	case "add":
		if err := acl.Add(scope, list, val, note); err != nil {
			return err.Error(), "err"
		}
		return "added " + val + " to " + scope + "/" + list, "ok"
	case "remove":
		if err := acl.Remove(scope, list, val); err != nil {
			return err.Error(), "err"
		}
		return "removed " + val + " from " + scope + "/" + list, "ok"
	default:
		return "unknown op: " + op, "err"
	}
}

// adminAuthOK accepts either:
//   - a valid mygrok_admin session cookie (issued by the magic-link
//     login flow on GET /admin/ips?key=...), or
//   - an Authorization: Basic ... header where the password matches
//     *authToken. Username is ignored — there's only one admin account.
func adminAuthOK(rawHeaders []byte) bool {
	if *authToken == "" {
		return false
	}
	if sid := readAdminCookie(rawHeaders); sid != "" && adminSess.valid(sid) {
		return true
	}
	var got string
	for _, line := range strings.Split(string(rawHeaders), "\r\n") {
		if strings.HasPrefix(strings.ToLower(line), "authorization:") {
			got = strings.TrimSpace(line[len("authorization:"):])
			break
		}
	}
	if !strings.HasPrefix(got, "Basic ") {
		return false
	}
	dec, err := base64.StdEncoding.DecodeString(strings.TrimSpace(got[len("Basic "):]))
	if err != nil {
		return false
	}
	parts := strings.SplitN(string(dec), ":", 2)
	if len(parts) != 2 {
		return false
	}
	return subtle.ConstantTimeCompare([]byte(parts[1]), []byte(*authToken)) == 1
}

// readAdminCookie pulls the mygrok_admin cookie value out of the raw
// request headers. Returns "" if missing. Doesn't validate — the caller
// runs that against adminSess.
func readAdminCookie(rawHeaders []byte) string {
	for _, line := range strings.Split(string(rawHeaders), "\r\n") {
		if !strings.HasPrefix(strings.ToLower(line), "cookie:") {
			continue
		}
		v := strings.TrimSpace(line[len("cookie:"):])
		for _, c := range strings.Split(v, ";") {
			c = strings.TrimSpace(c)
			eq := strings.IndexByte(c, '=')
			if eq < 0 {
				continue
			}
			if c[:eq] == adminCookieName {
				return c[eq+1:]
			}
		}
	}
	return ""
}

// writeHTTPLoginRedirect writes a 302 with both Location and Set-Cookie
// for the admin session. SameSite=Lax + HttpOnly + Secure is the right
// combination for our use — the cookie is only sent on same-site or
// top-level GET navigations, so cross-origin POSTs to /admin/ips can't
// piggyback on it (CSRF defence for the form).
func writeHTTPLoginRedirect(w io.Writer, location, sid string) {
	body := []byte("see " + location)
	hdr := fmt.Sprintf(
		"HTTP/1.1 302 Found\r\nLocation: %s\r\nSet-Cookie: %s=%s; Path=/; Max-Age=%d; HttpOnly; Secure; SameSite=Lax\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: %d\r\nCache-Control: no-store\r\nConnection: close\r\n\r\n",
		location, adminCookieName, sid, int(adminSessionTTL.Seconds()), len(body))
	_, _ = w.Write([]byte(hdr))
	_, _ = w.Write(body)
}

func writeHTTPUnauthorized(w io.Writer) {
	body := []byte("Unauthorized\n")
	hdr := fmt.Sprintf("HTTP/1.1 401 Unauthorized\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: %d\r\nWWW-Authenticate: Basic realm=\"mygrokd admin\"\r\nConnection: close\r\nCache-Control: no-store\r\n\r\n",
		len(body))
	_, _ = w.Write([]byte(hdr))
	_, _ = w.Write(body)
}

func writeHTTPRedirect(w io.Writer, location string) {
	body := []byte("see " + location)
	hdr := fmt.Sprintf("HTTP/1.1 302 Found\r\nLocation: %s\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: %d\r\nConnection: close\r\n\r\n",
		location, len(body))
	_, _ = w.Write([]byte(hdr))
	_, _ = w.Write(body)
}

// writeHTTPRedirectStatus is like writeHTTPRedirect but lets the caller
// pick the status code. Use 307 (or 308) for redirects that must
// preserve the original method + body (POST/PUT/etc.); 302 changes the
// follow-up to GET in many clients.
func writeHTTPRedirectStatus(w io.Writer, code int, location string) {
	body := []byte("see " + location)
	reason := "Temporary Redirect"
	if code == 308 {
		reason = "Permanent Redirect"
	}
	hdr := fmt.Sprintf("HTTP/1.1 %d %s\r\nLocation: %s\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: %d\r\nConnection: close\r\n\r\n",
		code, reason, location, len(body))
	_, _ = w.Write([]byte(hdr))
	_, _ = w.Write(body)
}

// readPostForm reads the request body using Content-Length from
// rawHeaders, then parses it as application/x-www-form-urlencoded. We
// cap the read at 1 MiB so a malformed admin POST can't OOM us.
func readPostForm(rawHeaders []byte, br *bufio.Reader) (url.Values, error) {
	cl := -1
	for _, line := range strings.Split(string(rawHeaders), "\r\n") {
		if strings.HasPrefix(strings.ToLower(line), "content-length:") {
			n, err := strconv.Atoi(strings.TrimSpace(line[len("content-length:"):]))
			if err == nil {
				cl = n
			}
			break
		}
	}
	if cl < 0 {
		return nil, fmt.Errorf("missing Content-Length")
	}
	if cl > 1<<20 {
		return nil, fmt.Errorf("body too large")
	}
	body := make([]byte, cl)
	if _, err := io.ReadFull(br, body); err != nil {
		return nil, err
	}
	return url.ParseQuery(string(body))
}

// renderAdminOverview builds the /admin/ips landing page: global allow/
// block rules at the top, then a list of all known tunnels (live + ones
// that have rules configured but no live session) linking into the
// per-tunnel page.
func renderAdminOverview(acl *ipACL, reg *registry, flash, flashClass string) []byte {
	global := acl.SnapshotGlobal()
	configured := acl.TunnelsConfigured()
	live := reg.activeSubdomains()

	var b strings.Builder
	fmt.Fprintf(&b, adminPageHeader, "tunnel."+*publicHost, "IP access control")
	b.WriteString(`<h1>IP access control</h1>`)
	b.WriteString(`<p class="muted" style="margin-bottom:8px"><a href="/admin/users">Users</a> · <a href="/admin/invites">Invites</a> · <a href="/admin/passkeys">Passkeys</a></p>`)
	fmt.Fprintf(&b, `<p class="muted">Restrict who can reach tunnels behind <code>tunnel.%s</code>. Default is open: a tunnel with no rules accepts every visitor.</p>`,
		html.EscapeString(*publicHost))
	if flash != "" {
		fmt.Fprintf(&b, `<div class="flash %s">%s</div>`, html.EscapeString(flashClass), html.EscapeString(flash))
	}

	// Global section
	b.WriteString(`<section><h2>Global rules <span class="muted">(apply to all tunnels)</span></h2>`)
	writeIPListBlock(&b, "Blocklist", "block", "", global.Blocked,
		"Matching IPs are rejected at the edge, on every tunnel. Use for known-bad ranges.")
	writeIPListBlock(&b, "Allowlist", "allow", "", global.Allowed,
		"If non-empty, only matching IPs may reach any tunnel — but a tunnel's own per-tunnel allowlist (if set) overrides this.")
	b.WriteString(`</section>`)

	// Tunnels section
	b.WriteString(`<section><h2>Per-tunnel rules</h2>`)
	b.WriteString(`<p class="blurb">Click a subdomain to manage its own allow/block lists. A tunnel with no per-tunnel rules inherits the global behaviour above.</p>`)

	all := mergeSorted(live, configured)
	if len(all) == 0 {
		b.WriteString(`<p class="empty">No tunnels currently registered or configured. Bring one up with <code>mygrok http &lt;port&gt; --subdomain=&lt;name&gt;</code>, or pre-configure rules for a future tunnel below.</p>`)
	} else {
		b.WriteString(`<table class="tunnels"><thead><tr><th>Subdomain</th><th>Status</th><th>Rules</th><th></th></tr></thead><tbody>`)
		liveSet := map[string]bool{}
		for _, s := range live {
			liveSet[s] = true
		}
		configuredSet := map[string]bool{}
		for _, s := range configured {
			configuredSet[s] = true
		}
		for _, s := range all {
			cls := "offline"
			status := "offline"
			if liveSet[s] {
				cls = "live"
				status = "live"
			}
			rules := "—"
			if configuredSet[s] {
				bk := acl.SnapshotTunnel(s)
				rules = fmt.Sprintf("%d allow / %d block", len(bk.Allowed), len(bk.Blocked))
			}
			fmt.Fprintf(&b,
				`<tr><td><code>%s</code></td><td class="status %s">%s</td><td>%s</td><td><a class="btn" href="/admin/ips/%s">Manage</a></td></tr>`,
				html.EscapeString(s), cls, status, html.EscapeString(rules), html.EscapeString(s))
		}
		b.WriteString(`</tbody></table>`)
	}

	// Quick-jump form for a not-yet-existing subdomain
	b.WriteString(`<form method="GET" action="" class="add jump" onsubmit="event.preventDefault(); var s=this.sub.value.trim(); if(s) location.href='/admin/ips/'+encodeURIComponent(s);">`)
	b.WriteString(`<input name="sub" placeholder="subdomain" pattern="[a-z0-9]([a-z0-9\-]{0,61}[a-z0-9])?" required>`)
	b.WriteString(`<button>Manage rules</button></form>`)

	b.WriteString(`</section>`)
	b.WriteString(adminPageFooter)
	return []byte(b.String())
}

// renderAdminTunnelPage is the per-tunnel page at /admin/ips/<sub>.
func renderAdminTunnelPage(sub string, acl *ipACL, reg *registry, locks *tunnelLocks, pks *passkeyStore, flash, flashClass string) []byte {
	bucket := acl.SnapshotTunnel(sub)
	live := reg.get(sub) != nil
	locked := locks.IsLocked(sub)
	allowedUserIDs := locks.AllowedUsers(sub)
	allUsers := pks.ListUsers()

	var b strings.Builder
	fmt.Fprintf(&b, adminPageHeader, "tunnel."+*publicHost, "IP rules · "+sub)
	fmt.Fprintf(&b, `<p class="back"><a class="back-link" href="/admin/ips">overview</a> · <a href="/admin/users">users</a> · <a href="/admin/invites">invites</a></p>`)
	fmt.Fprintf(&b, `<h1><code>%s</code></h1>`, html.EscapeString(sub))
	statusClass, statusLabel := "offline", "no live tunnel"
	if live {
		statusClass, statusLabel = "live", "live"
	}
	fmt.Fprintf(&b, `<p class="muted"><span class="pill %s">%s</span> Rules apply whether the tunnel is live or not — they take effect as soon as a client registers.</p>`,
		statusClass, html.EscapeString(statusLabel))
	if flash != "" {
		fmt.Fprintf(&b, `<div class="flash %s">%s</div>`, html.EscapeString(flashClass), html.EscapeString(flash))
	}

	// Passkey gate / per-user grant
	b.WriteString(`<section><h2>Passkey gate</h2>`)
	if locked {
		fmt.Fprintf(&b, `<p class="blurb"><span class="pill live">locked</span> Only the listed users can pass the gate. Visitors are redirected to <code>/auth</code> to authenticate; only matching credentials open the tunnel.</p>`)
	} else {
		b.WriteString(`<p class="blurb">Currently open: anyone who passes the IP rules can reach this tunnel. Grant a user below to start gating it.</p>`)
	}
	allowedSet := map[string]bool{}
	for _, uid := range allowedUserIDs {
		allowedSet[uid] = true
	}
	if locked {
		b.WriteString(`<table><thead><tr><th>User</th><th></th></tr></thead><tbody>`)
		for _, uid := range allowedUserIDs {
			name := uid
			if u := pks.FindUser(uid); u != nil {
				name = u.Name
			}
			fmt.Fprintf(&b,
				`<tr><td><strong>%s</strong> <span class="muted">(%s)</span></td>`+
					`<td><form method="POST" action="/admin/grants" class="inline">`+
					`<input type="hidden" name="sub" value="%s">`+
					`<input type="hidden" name="user_id" value="%s">`+
					`<input type="hidden" name="op" value="revoke">`+
					`<button class="danger">Revoke</button></form></td></tr>`,
				html.EscapeString(name), html.EscapeString(shortID(uid)),
				html.EscapeString(sub), html.EscapeString(uid))
		}
		b.WriteString(`</tbody></table>`)
	}
	// Grant form: select-from-users
	if len(allUsers) == 0 {
		b.WriteString(`<p class="empty">No users yet. <a href="/admin/invites">Issue an invite →</a></p>`)
	} else {
		var ungranted []pkUserRecord
		for _, u := range allUsers {
			if !allowedSet[u.ID] {
				ungranted = append(ungranted, u)
			}
		}
		if len(ungranted) > 0 {
			fmt.Fprintf(&b, `<form method="POST" action="/admin/grants" class="add"><input type="hidden" name="sub" value="%s"><input type="hidden" name="op" value="grant"><select name="user_id" required>`,
				html.EscapeString(sub))
			b.WriteString(`<option value="">— pick a user —</option>`)
			for _, u := range ungranted {
				fmt.Fprintf(&b, `<option value="%s">%s</option>`,
					html.EscapeString(u.ID), html.EscapeString(u.Name))
			}
			b.WriteString(`</select><button>Grant</button></form>`)
		} else if locked {
			b.WriteString(`<p class="muted" style="margin-top:8px">Every existing user has access. Issue an invite to add another.</p>`)
		}
	}
	if locked {
		fmt.Fprintf(&b, `<form method="POST" action="/admin/locks" style="margin-top:12px"><input type="hidden" name="sub" value="%s"><input type="hidden" name="op" value="unlock"><button class="danger">Unlock (clear all grants)</button></form>`, html.EscapeString(sub))
	}
	b.WriteString(`</section>`)

	b.WriteString(`<section>`)
	writeIPListBlock(&b, "Allowlist", "allow", "", bucket.Allowed,
		"If non-empty, only IPs in this list can reach this tunnel (per-tunnel allowlist overrides any global allowlist).")
	writeIPListBlock(&b, "Blocklist", "block", "", bucket.Blocked,
		"Matching IPs are rejected for this tunnel, regardless of the allowlist.")
	b.WriteString(`</section>`)
	b.WriteString(adminPageFooter)
	return []byte(b.String())
}

// writeIPListBlock renders one allow- or block-list block. The form
// action is empty so the POST goes back to the current URL — works for
// both the global page and the per-tunnel page without needing an
// explicit scope field.
func writeIPListBlock(b *strings.Builder, title, list, _formAction string, entries []ipEntry, blurb string) {
	fmt.Fprintf(b, `<div class="block"><h3>%s <span class="muted">(%d)</span></h3>`, html.EscapeString(title), len(entries))
	fmt.Fprintf(b, `<p class="blurb">%s</p>`, html.EscapeString(blurb))
	if len(entries) == 0 {
		b.WriteString(`<p class="empty">— empty —</p>`)
	} else {
		b.WriteString(`<table>`)
		for _, e := range entries {
			fmt.Fprintf(b,
				`<tr><td><code>%s</code></td><td class="note">%s</td><td><form method="POST" class="inline">`+
					`<input type="hidden" name="list" value="%s">`+
					`<input type="hidden" name="op" value="remove">`+
					`<input type="hidden" name="value" value="%s">`+
					`<button class="danger">Remove</button></form></td></tr>`,
				html.EscapeString(e.Raw),
				html.EscapeString(e.Note),
				html.EscapeString(list),
				html.EscapeString(e.Raw),
			)
		}
		b.WriteString(`</table>`)
	}
	fmt.Fprintf(b, `<form method="POST" class="add">`+
		`<input type="hidden" name="list" value="%s">`+
		`<input type="hidden" name="op" value="add">`+
		`<input name="value" placeholder="1.2.3.4 or 10.0.0.0/8" required>`+
		`<input name="note" placeholder="optional note">`+
		`<button>Add</button></form></div>`,
		html.EscapeString(list))
}

// mergeSorted returns the sorted union of two already-sorted string
// slices.
func mergeSorted(a, b []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range a {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	for _, s := range b {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	sort.Strings(out)
	return out
}

// adminPageHeader takes (publicHost, pageTitle). Used by both the
// overview and per-tunnel pages so the chrome stays consistent.
const adminPageHeader = `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<title>%[2]s · %[1]s</title>
<style>
  :root {
    color-scheme: dark light;
    --bg: #07090d;
    --bg-grid: rgba(120,140,170,0.05);
    --panel: #0d1119;
    --panel-2: #11151f;
    --hairline: #1a2030;
    --hairline-2: #2a3245;
    --ink: #e7eaf2;
    --ink-dim: #8a93a6;
    --ink-dimmer: #5b6478;
    --signal: #b8f068;
    --signal-soft: rgba(184,240,104,0.10);
    --signal-line: rgba(184,240,104,0.35);
    --danger: #ff8a8a;
    --danger-soft: rgba(255,138,138,0.10);
    --danger-line: rgba(255,138,138,0.35);
    --warn: #ffb86b;
  }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; }
  body {
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-feature-settings: "calt", "ss01";
    font-size: 14px;
    line-height: 1.55;
    background: var(--bg);
    color: var(--ink);
    min-height: 100vh;
    background-image:
      radial-gradient(circle at 1px 1px, var(--bg-grid) 1px, transparent 0);
    background-size: 24px 24px;
    background-position: -1px -1px;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }
  .wrap { max-width: 880px; margin: 0 auto; padding: 56px 24px 64px; }
  ::selection { background: var(--signal); color: #0a0d12; }

  @keyframes pulse { 0%%,100%% { opacity: 1; } 50%% { opacity: 0.35; } }
  h1 {
    font-family: ui-monospace, monospace;
    font-weight: 700; font-size: 30px; letter-spacing: -0.02em;
    margin: 0 0 6px;
    display: flex; align-items: center; gap: 14px;
  }
  h1::before {
    content: ""; width: 8px; height: 8px; border-radius: 50%%;
    background: var(--signal); box-shadow: 0 0 10px var(--signal);
    animation: pulse 2.4s ease-in-out infinite;
    flex: none;
  }
  h2 {
    font-size: 11px; font-weight: 700; letter-spacing: 0.20em;
    text-transform: uppercase; margin: 0; color: var(--ink);
    display: flex; align-items: baseline; gap: 10px;
  }
  h2 .muted { letter-spacing: 0.04em; text-transform: none; }
  h3 { font-size: 12px; font-weight: 600; letter-spacing: 0.14em;
    text-transform: uppercase; margin: 22px 0 6px; color: var(--ink); }
  .muted { color: var(--ink-dim); font-weight: 400; font-size: 13px; }

  /* Section panels */
  section {
    background: var(--panel);
    border: 1px solid var(--hairline);
    border-radius: 6px;
    padding: 24px 28px 20px;
    margin: 18px 0;
    position: relative;
  }
  section::before {
    content: ""; position: absolute; inset: 0;
    border-radius: 6px; pointer-events: none;
    box-shadow: inset 0 1px 0 rgba(255,255,255,0.03);
  }
  section > h2 { margin-bottom: 4px; }

  .block { padding: 14px 0 18px; border-bottom: 1px dashed var(--hairline-2); }
  .block:last-child { border-bottom: 0; padding-bottom: 4px; }
  .blurb { margin: 4px 0 14px; color: var(--ink-dim); font-size: 12.5px; }
  .empty {
    color: var(--ink-dimmer); font-style: italic; padding: 6px 0; font-size: 13px;
  }

  /* Tables */
  table { width: 100%%; border-collapse: collapse; margin: 6px 0 4px; }
  th {
    text-align: left; font-weight: 600; font-size: 10.5px;
    letter-spacing: 0.18em; text-transform: uppercase;
    padding: 10px 8px; color: var(--ink-dimmer);
    border-bottom: 1px solid var(--hairline-2);
  }
  td {
    padding: 12px 8px; border-bottom: 1px solid var(--hairline);
    vertical-align: middle; font-size: 13.5px;
  }
  tr:last-child td { border-bottom: 0; }
  td.note { font-size: 12.5px; color: var(--ink-dim); }
  td.status { font-size: 12px; letter-spacing: 0.14em; text-transform: uppercase; font-weight: 600; }
  td.status.live { color: var(--signal); }
  td.status.live::before {
    content: ""; display: inline-block; width: 6px; height: 6px; border-radius: 50%%;
    background: var(--signal); box-shadow: 0 0 8px var(--signal);
    margin-right: 8px; vertical-align: middle;
    animation: pulse 2.4s ease-in-out infinite;
  }
  td.status.offline { color: var(--ink-dimmer); }
  td.status.offline::before {
    content: ""; display: inline-block; width: 6px; height: 6px; border-radius: 50%%;
    background: var(--ink-dimmer); margin-right: 8px; vertical-align: middle;
  }
  table.tunnels td:last-child { text-align: right; }
  table.tunnels td:first-child { font-weight: 600; }

  /* Code chips */
  code {
    font-family: ui-monospace, monospace;
    font-size: 12.5px; font-weight: 500;
    background: var(--panel-2);
    color: var(--ink);
    padding: 2px 8px;
    border: 1px solid var(--hairline-2);
    border-radius: 3px;
  }

  /* Forms */
  form.inline { display: inline; }
  form.add { display: flex; gap: 8px; align-items: center; flex-wrap: wrap; margin-top: 4px; }
  form.add input[name=value] { flex: 1 1 220px; min-width: 0; }
  form.add input[name=note]  { flex: 2 1 240px; min-width: 0; }
  form.jump { margin-top: 18px; padding-top: 16px; border-top: 1px dashed var(--hairline-2); }

  input, button, a.btn {
    font: inherit;
    font-family: ui-monospace, monospace;
    font-size: 13px;
  }
  input {
    padding: 9px 12px;
    background: transparent;
    color: var(--ink);
    border: 1px solid var(--hairline-2);
    border-radius: 3px;
    transition: border-color 120ms ease, box-shadow 120ms ease;
  }
  input::placeholder { color: var(--ink-dimmer); }
  input:focus {
    outline: none;
    border-color: var(--signal-line);
    box-shadow: 0 0 0 3px var(--signal-soft);
  }

  button, a.btn {
    padding: 9px 16px;
    background: transparent;
    color: var(--ink);
    border: 1px solid var(--hairline-2);
    border-radius: 3px;
    cursor: pointer; text-decoration: none; display: inline-block;
    font-weight: 500;
    letter-spacing: 0.02em;
    transition: border-color 120ms ease, color 120ms ease, background 120ms ease;
  }
  button:hover, a.btn:hover {
    border-color: var(--signal-line);
    color: var(--signal);
    background: var(--signal-soft);
  }
  button:focus-visible, a.btn:focus-visible {
    outline: none;
    border-color: var(--signal);
    box-shadow: 0 0 0 3px var(--signal-soft);
  }
  button.danger {
    background: transparent;
    color: var(--danger);
    border-color: var(--danger-line);
  }
  button.danger:hover {
    background: var(--danger-soft);
    border-color: var(--danger);
  }

  /* Pills (used outside tables, e.g. on tunnel pages) */
  .pill {
    display: inline-flex; align-items: center; gap: 6px;
    padding: 3px 10px; border-radius: 3px;
    font-size: 10.5px; font-weight: 600;
    letter-spacing: 0.16em; text-transform: uppercase;
    border: 1px solid transparent; vertical-align: middle;
    margin-right: 6px;
  }
  .pill.live {
    background: var(--signal-soft); color: var(--signal);
    border-color: var(--signal-line);
  }
  .pill.live::before {
    content: ""; width: 6px; height: 6px; border-radius: 50%%;
    background: var(--signal); box-shadow: 0 0 8px var(--signal);
    animation: pulse 2.4s ease-in-out infinite;
  }
  .pill.offline {
    background: rgba(255,255,255,0.02); color: var(--ink-dim);
    border-color: var(--hairline-2);
  }

  /* Links / nav */
  a { color: var(--ink); text-decoration: none; border-bottom: 1px solid var(--hairline-2); transition: border-color 120ms; }
  a:hover { border-bottom-color: var(--signal); color: var(--signal); }
  .back { margin: 0 0 18px; font-size: 12px; letter-spacing: 0.06em; color: var(--ink-dim); }
  .back a { color: var(--ink-dim); border-bottom: 0; }
  .back .back-link::before { content: "← "; opacity: 0.6; }
  .back a:hover { color: var(--signal); }

  /* Copy-to-clipboard button */
  .copy-btn {
    display: inline-flex; align-items: center; justify-content: center;
    font: inherit; font-size: 11.5px; line-height: 1;
    padding: 4px 9px;
    background: transparent; color: var(--ink-dim);
    border: 1px solid var(--hairline-2); border-radius: 3px;
    cursor: pointer; user-select: none;
    transition: color 120ms, border-color 120ms;
  }
  .copy-btn:hover { color: var(--signal); border-color: var(--signal-line); }
  .copy-btn.copied { color: var(--signal); border-color: var(--signal-line); }
  .copy-row { display: flex; flex-wrap: wrap; align-items: center; gap: 8px; }
  .copy-row code {
    font-size: 12.5px; padding: 4px 8px;
    background: rgba(255,255,255,0.04);
    border-radius: 3px;
    user-select: all; word-break: break-all;
  }
  .flash .copy-row { margin-top: 8px; }
  .flash-title { font-weight: 500; }

  /* Flash */
  .flash {
    padding: 12px 16px;
    border-radius: 4px;
    margin: 16px 0 0;
    background: var(--signal-soft);
    color: var(--signal);
    border: 1px solid var(--signal-line);
    font-size: 13px;
  }
  .flash.err {
    background: var(--danger-soft);
    color: var(--danger);
    border-color: var(--danger-line);
  }

  /* Footer */
  .footer {
    margin-top: 48px; padding-top: 20px;
    border-top: 1px dashed var(--hairline-2);
    font-size: 11.5px; letter-spacing: 0.04em;
    color: var(--ink-dimmer);
  }
  .footer a { color: var(--ink-dim); border-bottom: 0; }
  .footer a:hover { color: var(--signal); }

  /* Light mode — equally polished, paper-and-ink operator's notebook */
  @media (prefers-color-scheme: light) {
    :root {
      --bg: #f7f5f0;
      --bg-grid: rgba(20,30,50,0.06);
      --panel: #ffffff;
      --panel-2: #f1efe9;
      --hairline: #e3dfd5;
      --hairline-2: #cbc6b8;
      --ink: #1a1d24;
      --ink-dim: #5b6175;
      --ink-dimmer: #8a8f9d;
      --signal: #2f7a2f;
      --signal-soft: rgba(47,122,47,0.08);
      --signal-line: rgba(47,122,47,0.30);
      --danger: #b3261e;
      --danger-soft: rgba(179,38,30,0.06);
      --danger-line: rgba(179,38,30,0.28);
    }
    section::before { box-shadow: inset 0 1px 0 rgba(0,0,0,0.02); }
    ::selection { background: var(--signal); color: #fff; }
  }

  @media (max-width: 600px) {
    .wrap { padding: 32px 16px 48px; }
    section { padding: 18px 18px 14px; }
    h1 { font-size: 24px; }
    table.tunnels td:last-child { padding-left: 0; }
  }
</style>
</head><body><div class="wrap">
`

const adminPageFooter = `<p class="footer">mygrokd admin · session via <code>mygrok admin</code> CLI or HTTP basic auth (password = <code>MYGROK_AUTHTOKEN</code>).</p>
</div>
<script>
(function () {
  document.addEventListener('click', function (e) {
    var btn = e.target.closest('[data-copy]');
    if (!btn) return;
    e.preventDefault();
    var text = btn.getAttribute('data-copy');
    var done = function () {
      if (!btn.dataset.origLabel) btn.dataset.origLabel = btn.textContent;
      btn.textContent = 'copied';
      btn.classList.add('copied');
      clearTimeout(btn._copyT);
      btn._copyT = setTimeout(function () {
        btn.textContent = btn.dataset.origLabel;
        btn.classList.remove('copied');
      }, 1400);
    };
    var fallback = function () {
      var ta = document.createElement('textarea');
      ta.value = text;
      ta.style.position = 'fixed'; ta.style.left = '-9999px';
      document.body.appendChild(ta);
      ta.select();
      try { document.execCommand('copy'); done(); } catch (err) {}
      document.body.removeChild(ta);
    };
    if (navigator.clipboard && window.isSecureContext) {
      navigator.clipboard.writeText(text).then(done).catch(fallback);
    } else {
      fallback();
    }
  });
})();
</script>
</body></html>`

// renderAdminPasskeysPage shows registered credentials and the
// "register a new passkey" form. The actual WebAuthn ceremony is
// driven by inline JS that talks to /admin/passkeys/{begin,finish}.
func renderAdminPasskeysPage(pks *passkeyStore, flash, flashClass string) []byte {
	creds := pks.ListCredentials("")
	var b strings.Builder
	fmt.Fprintf(&b, adminPageHeader, "tunnel."+*publicHost, "Passkeys")
	b.WriteString(`<p class="back"><a class="back-link" href="/admin/ips">overview</a></p>`)
	b.WriteString(`<h1>Passkeys</h1>`)
	b.WriteString(`<p class="muted">Register one or more passkeys (Touch ID, Face ID, Windows Hello, hardware key) here, then enable the per-tunnel passkey gate on any tunnel that should require one to access.</p>`)
	if flash != "" {
		fmt.Fprintf(&b, `<div class="flash %s">%s</div>`, html.EscapeString(flashClass), html.EscapeString(flash))
	}

	b.WriteString(`<section><h2>Registered <span class="muted">(`)
	fmt.Fprintf(&b, "%d", len(creds))
	b.WriteString(`)</span></h2>`)
	if len(creds) == 0 {
		b.WriteString(`<p class="empty">No passkeys yet. Use the form below to register one.</p>`)
	} else {
		b.WriteString(`<table><thead><tr><th>Label</th><th>ID</th><th>Created</th><th>Last used</th><th></th></tr></thead><tbody>`)
		for _, c := range creds {
			lastUsed := "never"
			if !c.LastUsedAt.IsZero() {
				lastUsed = c.LastUsedAt.UTC().Format("2006-01-02 15:04 UTC")
			}
			fmt.Fprintf(&b,
				`<tr><td>%s</td><td><code>%s</code></td><td>%s</td><td>%s</td>`+
					`<td><form method="POST" action="/admin/passkeys/delete" class="inline" onsubmit="return confirm('Delete this passkey?');">`+
					`<input type="hidden" name="id" value="%s"><button class="danger">Delete</button></form></td></tr>`,
				html.EscapeString(c.Label), html.EscapeString(shortID(c.ID)),
				c.Created.UTC().Format("2006-01-02 15:04 UTC"),
				html.EscapeString(lastUsed),
				html.EscapeString(c.ID))
		}
		b.WriteString(`</tbody></table>`)
	}
	b.WriteString(`</section>`)

	b.WriteString(`<section><h2>Register a new passkey</h2>`)
	b.WriteString(`<p class="blurb">Pick a label that helps you recognise this device later, then click Register and follow your browser's passkey prompt.</p>`)
	b.WriteString(`<form id="reg-form" class="add" onsubmit="return false;">`)
	b.WriteString(`<input id="reg-label" placeholder="e.g. MacBook Pro" required>`)
	b.WriteString(`<button id="reg-btn">Register passkey</button>`)
	b.WriteString(`</form>`)
	b.WriteString(`<p id="reg-status" class="muted" style="margin-top:8px"></p>`)
	b.WriteString(`</section>`)

	b.WriteString(passkeyJSShim)
	b.WriteString(`<script>
    (function(){
      var btn = document.getElementById('reg-btn');
      var label = document.getElementById('reg-label');
      var status = document.getElementById('reg-status');
      btn.addEventListener('click', async function(){
        var name = label.value.trim();
        if (!name) { status.textContent = 'enter a label first'; return; }
        status.textContent = 'starting…';
        try {
          var r = await fetch('/admin/passkeys/begin', { method:'POST', credentials:'same-origin' });
          if (!r.ok) throw new Error('begin: HTTP ' + r.status);
          var opts = await r.json();
          // Convert base64url binary fields to ArrayBuffer for the WebAuthn API.
          opts.publicKey.challenge = b64uDecode(opts.publicKey.challenge);
          opts.publicKey.user.id = b64uDecode(opts.publicKey.user.id);
          if (opts.publicKey.excludeCredentials) {
            opts.publicKey.excludeCredentials.forEach(function(c){ c.id = b64uDecode(c.id); });
          }
          status.textContent = 'follow the browser prompt…';
          var cred = await navigator.credentials.create({ publicKey: opts.publicKey });
          // Re-encode binary fields for transport back.
          var payload = {
            label: name,
            credential: {
              id: cred.id,
              rawId: b64uEncode(cred.rawId),
              type: cred.type,
              response: {
                clientDataJSON: b64uEncode(cred.response.clientDataJSON),
                attestationObject: b64uEncode(cred.response.attestationObject)
              },
              clientExtensionResults: cred.getClientExtensionResults ? cred.getClientExtensionResults() : {}
            }
          };
          var r2 = await fetch('/admin/passkeys/finish', {
            method:'POST', credentials:'same-origin',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
          });
          var body = await r2.json().catch(function(){return{};});
          if (!r2.ok || body.ok === false) {
            status.textContent = 'failed: ' + (body.error || ('HTTP ' + r2.status));
            return;
          }
          status.textContent = 'registered. reloading…';
          location.reload();
        } catch (e) {
          status.textContent = 'failed: ' + e.message;
        }
      });
    })();
  </script>`)
	b.WriteString(adminPageFooter)
	return []byte(b.String())
}

func renderAuthLoginPage(returnURL string) string {
	var b strings.Builder
	fmt.Fprintf(&b, adminPageHeader, "tunnel."+*publicHost, "Sign in")
	b.WriteString(`<h1>Sign in with a passkey</h1>`)
	b.WriteString(`<p class="muted">This tunnel is locked. Authenticate with one of your registered passkeys to continue.</p>`)
	b.WriteString(`<section>`)
	fmt.Fprintf(&b, `<form id="login-form" onsubmit="return false;"><input type="hidden" id="ret" value="%s">`,
		html.EscapeString(returnURL))
	b.WriteString(`<button id="login-btn">Authenticate</button></form>`)
	b.WriteString(`<p id="login-status" class="muted" style="margin-top:12px"></p>`)
	b.WriteString(`</section>`)
	b.WriteString(`<p class="muted" style="margin-top:24px;font-size:12px">Got a new device? Sign in here, then go to <a href="/account">/account</a> to register another passkey on it.</p>`)
	b.WriteString(passkeyJSShim)
	b.WriteString(`<script>
    (function(){
      var btn = document.getElementById('login-btn');
      var ret = document.getElementById('ret').value;
      var status = document.getElementById('login-status');
      async function go() {
        status.textContent = 'starting…';
        try {
          var qs = ret ? ('?return=' + encodeURIComponent(ret)) : '';
          var r = await fetch('/auth/begin' + qs, { method:'POST', credentials:'same-origin' });
          if (!r.ok) throw new Error('begin: HTTP ' + r.status);
          var opts = await r.json();
          opts.publicKey.challenge = b64uDecode(opts.publicKey.challenge);
          if (opts.publicKey.allowCredentials) {
            opts.publicKey.allowCredentials.forEach(function(c){ c.id = b64uDecode(c.id); });
          }
          status.textContent = 'follow the browser prompt…';
          var asn = await navigator.credentials.get({ publicKey: opts.publicKey });
          var payload = {
            id: asn.id,
            rawId: b64uEncode(asn.rawId),
            type: asn.type,
            response: {
              clientDataJSON: b64uEncode(asn.response.clientDataJSON),
              authenticatorData: b64uEncode(asn.response.authenticatorData),
              signature: b64uEncode(asn.response.signature),
              userHandle: asn.response.userHandle ? b64uEncode(asn.response.userHandle) : ''
            },
            clientExtensionResults: asn.getClientExtensionResults ? asn.getClientExtensionResults() : {}
          };
          var r2 = await fetch('/auth/finish', {
            method:'POST', credentials:'same-origin',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
          });
          var body = await r2.json().catch(function(){return{};});
          if (!r2.ok || body.ok === false) {
            status.textContent = 'failed: ' + (body.error || ('HTTP ' + r2.status));
            return;
          }
          status.textContent = 'success — redirecting…';
          location.href = body.return || '/';
        } catch (e) {
          status.textContent = 'failed: ' + e.message;
        }
      }
      btn.addEventListener('click', go);
      // Auto-trigger on page load too — most users want immediate prompt.
      setTimeout(go, 200);
    })();
  </script>`)
	b.WriteString(adminPageFooter)
	return b.String()
}

func renderAuthErrorPage(msg string) string {
	var b strings.Builder
	fmt.Fprintf(&b, adminPageHeader, "tunnel."+*publicHost, "Sign in")
	b.WriteString(`<h1>Sign in unavailable</h1>`)
	fmt.Fprintf(&b, `<p>%s</p>`, html.EscapeString(msg))
	b.WriteString(adminPageFooter)
	return b.String()
}

// passkeyJSShim is a tiny base64url helper shared by the registration
// and login pages. WebAuthn JS APIs traffic in ArrayBuffers; the wire
// format is base64url. Inline so we don't ship a separate JS file.
const passkeyJSShim = `<script>
function b64uDecode(s) {
  s = s.replace(/-/g,'+').replace(/_/g,'/');
  while (s.length % 4) s += '=';
  return Uint8Array.from(atob(s), function(c){ return c.charCodeAt(0); });
}
function b64uEncode(buf) {
  return btoa(String.fromCharCode.apply(null, new Uint8Array(buf)))
    .replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
}
</script>`

func shortID(id string) string {
	if len(id) <= 16 {
		return id
	}
	return id[:8] + "…" + id[len(id)-8:]
}

func serveBinary(conn net.Conn, name string) {
	if !validBinaryName(name) {
		writeHTTP(conn, 404, "text/plain; charset=utf-8", []byte("not found"))
		return
	}
	f, err := clientFS.Open("embed/clients/" + name)
	if err != nil {
		writeHTTP(conn, 404, "text/plain; charset=utf-8",
			[]byte("binary not available: "+name+"\nrebuild mygrokd with the embedded clients."))
		return
	}
	defer f.Close()
	st, err := f.(fs.File).Stat()
	if err != nil {
		writeHTTP(conn, 500, "text/plain; charset=utf-8", []byte("stat error"))
		return
	}
	header := fmt.Sprintf("HTTP/1.1 200 OK\r\nContent-Type: application/octet-stream\r\nContent-Length: %d\r\nContent-Disposition: attachment; filename=\"mygrok\"\r\nConnection: close\r\n\r\n",
		st.Size())
	if _, err := conn.Write([]byte(header)); err != nil {
		return
	}
	_, _ = io.Copy(conn, f)
}

// validBinaryName allows mygrok-<os>-<arch> only.
func validBinaryName(name string) bool {
	if !strings.HasPrefix(name, "mygrok-") {
		return false
	}
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z':
		case r >= '0' && r <= '9':
		case r == '-':
		default:
			return false
		}
	}
	return true
}

func parseRequestLine(raw []byte) (method, path string) {
	br := bufio.NewReader(bytes.NewReader(raw))
	line, err := br.ReadString('\n')
	if err != nil && line == "" {
		return "", ""
	}
	parts := strings.SplitN(strings.TrimRight(line, "\r\n"), " ", 3)
	if len(parts) < 2 {
		return "", ""
	}
	return parts[0], parts[1]
}

// writeHTTP writes a complete HTTP/1.1 response (closes the connection).
func writeHTTP(w io.Writer, code int, contentType string, body []byte) {
	status := statusText(code)
	// HSTS whenever a TLS listener exists. Browsers ignore the header on a
	// plaintext response, so sending it unconditionally is harmless and
	// saves threading "was this TLS?" through every caller.
	hsts := ""
	if *httpsAddr != "" {
		hsts = "Strict-Transport-Security: max-age=31536000\r\n"
	}
	hdr := fmt.Sprintf("HTTP/1.1 %d %s\r\nContent-Type: %s\r\nContent-Length: %d\r\nConnection: close\r\nCache-Control: no-store\r\n%s\r\n",
		code, status, contentType, len(body), hsts)
	_, _ = w.Write([]byte(hdr))
	_, _ = w.Write(body)
}

// sameOriginPOST guards admin mutations against cross-site requests.
//
// The admin session cookie is SameSite=Lax, which already blocks
// cross-site POSTs — but HTTP Basic auth is also accepted, and browsers
// replay cached Basic credentials on any request to the realm regardless of
// SameSite. So a page on another site could POST to /admin/ips and have it
// authenticate. Checking Origin (falling back to Referer) closes that
// without needing a token in every form.
//
// A missing Origin *and* Referer is allowed: that's what non-browser
// clients like `mygrok admin` and curl send, and they aren't the threat
// here — a cross-site attacker cannot suppress both from a browser.
func sameOriginPOST(rawHeaders []byte, publicHost string) bool {
	origin, referer := "", ""
	for _, line := range strings.Split(string(rawHeaders), "\r\n") {
		lower := strings.ToLower(line)
		switch {
		case strings.HasPrefix(lower, "origin:"):
			origin = strings.TrimSpace(line[len("origin:"):])
		case strings.HasPrefix(lower, "referer:"):
			referer = strings.TrimSpace(line[len("referer:"):])
		}
	}
	check := origin
	if check == "" {
		check = referer
	}
	if check == "" {
		return true
	}
	u, err := url.Parse(check)
	if err != nil {
		return false
	}
	return strings.ToLower(u.Hostname()) == "tunnel."+strings.ToLower(publicHost)
}

func statusText(code int) string {
	switch code {
	case 200:
		return "OK"
	case 400:
		return "Bad Request"
	case 404:
		return "Not Found"
	case 500:
		return "Internal Server Error"
	case 502:
		return "Bad Gateway"
	default:
		return "OK"
	}
}

// keep linter happy if any helper goes unused during refactors
var _ = time.Now

// clientServerAddr is the host:port a client should dial to reach this
// server's control plane. --tunnel is a listen address (":7000", or
// "0.0.0.0:7000"), which is not something a client can connect to — the
// host part has to be the management hostname.
func clientServerAddr() string {
	port := "7000"
	if _, p, err := net.SplitHostPort(*tunnelAddr); err == nil && p != "" {
		port = p
	}
	return net.JoinHostPort("tunnel."+*publicHost, port)
}
